name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Restore Tools
      run: dotnet tool restore
    - name: Restore Packages
      run: dotnet packet install
    - name: Build with dotnet
      run: dotnet build --configuration Release
